import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import { cookies } from 'next/headers';
import { UserProvider } from '@auth0/nextjs-auth0/client';

const manrope = Manrope({
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get('theme')?.value
    ? (cookies().get('theme')!.value as 'dark' | 'light')
    : 'system';

  return (
    <html lang="en" className={`${theme}`}>
      <body className={manrope.className}>
        <UserProvider>
          <Header selectedTheme={theme} />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
